#公用环境
spring:
  profiles:
    active: dev
  thymeleaf:
   enabled: true
   #默认是classpath:/templates/
   prefix: classpath:/templates/
   suffix: .html
   mode: HTML
   encoding: UTF-8
   servlet:
     content-type: text/html
  application:
    name: EasyBlog
  #邮件相关配置
  mail:
    host: smtp.qq.com
    password: ceozdvepgtlydihg   #这里的password是生成的授权码，不是账户密码
    username: huangxin9830@qq.com  #发送邮件的账户名
    properties:      #properties的值应该是一个Map
      mail.smpt.ssl: true       #设置使用SSL安全协议
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
logging:
  config: classpath:logback-spring.xml
#七牛云配置
qiniu:
  accessKey: vRxHtqsnLfzK2h2DTGcEfFlLLDDNgqAvoZf0H08D
  secretKey: 5No0lIzPOv2pYDX9wPkFFh_kE99lvpPia0nA0ZPH
  bucket: blog_album
  path: http://poag7m5q9.bkt.clouddn.com
