#公用环境
spring:
  profiles:
    active: dev
  thymeleaf:
   enabled: true
   #默认是classpath:/templates/
   prefix: classpath:/templates/
   suffix: .html
   mode: LEGACYHTML5
   encoding: UTF-8
   servlet:
     content-type: text/html
  application:
    name: EasyBlog
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
logging:
  config: classpath:logback-spring.xml